apiVersion: v2
name: external-secrets
description: A wrapper chart for External Sercrets deployment.
version: 0.1.0
dependencies:
  - name: external-secrets
    version: "2.0.1"
    repository: "https://charts.external-secrets.io/"
