[project]
name = "demo-cluster-iac"
revision = "1.0"

[profiles.default]
HCLOUD_TOKEN = { description = "Hetzner cloud api token", required=true}
TAILSCALE_API_KEY = { description = "Token for authenticating requests to the Tailscale API", required=true}
TAILSCALE_TAILNET = { description = "The tailnet ID", required = true}
