apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway-api-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-11"
spec:
  project: platform
  source:
    repoURL: https://github.com/Aleksuo/demo-cluster-iac.git
    targetRevision: HEAD
    path: kubernetes/addons/gateway-api-crds
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true