apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: internal-gateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-9"
spec:
  project: platform
  source:
    repoURL: https://github.com/Aleksuo/demo-cluster-iac.git
    targetRevision: HEAD
    path: kubernetes/addons/internal-gateway
  destination:
    server: https://kubernetes.default.svc
    namespace: internal-gateway
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true