apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: internal-gateway
spec:
  gatewayClassName: cilium
  listeners:
    - name: http
      protocol: HTTP
      port: 30080
      hostname: "*.internal.aleksuo.dev"
      allowedRoutes:
        namespaces:
          from: All
    - name: https
      protocol: HTTPS
      port: 30443
      hostname: "*.internal.aleksuo.dev"
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: internal-aleksuo-dev-tls
      allowedRoutes:
        namespaces:
          from: All